additions based on update
Reledia/glow.yazi pull request #6
Opened 2024-08-28 18:01 UTC by AnirudhG07

Based on the recent PR [#1550](https://github.com/sxyazi/yazi/pull/1550), glow.yazi should also be updated to avoid any future complications.

Thanks

2024-08-28 18:10 UTC, AnirudhG07 commented
And also ya pack download instructions.

2024-08-28 18:44 UTC, Reledia requested changes
Little changes in the readme. Remove any mentions of cloning the repo, thanks

2024-08-28 18:44 UTC, Reledia commented on README.md
>  Plugin for [Yazi](https://github.com/sxyazi/yazi) to preview markdown files with [glow](https://github.com/charmbracelet/glow). To install, clone the repo inside your `~/.config/yazi/plugins/`:
Remove completely the part related to cloning the repo and leave only the `ya pack` command

2024-08-29 05:19 UTC, AnirudhG07 commented
I hope this is fine. If any edits needed, you can change it suitable to u. 
Thanks

2024-08-29 05:38 UTC, merged

2024-08-29 05:38 UTC, Reledia commented
It's perfect now